version: '3'

services:
  server_1:
    image: nginx
    container_name: 'server_1'
    volumes:
      - ./server_1:/usr/share/nginx/html
    ports:
      - 7000:80

  server_2:
    image: nginx
    container_name: 'server_2'
    volumes:
      - ./server_2:/usr/share/nginx/html
    ports:
      - 7001:80

  reverse_proxy:
    image: nginx
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80