version: '3'

services:
  balancer:
    container_name: 'balancer'
    image: nginx
    volumes:
      - ./balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - balancer

  server_1:
    container_name: 'server_1'
    image: nginx
    volumes:
      - ./server_1:/usr/share/nginx/html
    ports:
      - 7000:80
    networks:
      - balancer

  server_2:
    container_name: 'server_2'
    image: nginx
    volumes:
      - ./server_2:/usr/share/nginx/html
    ports:
      - 7001:80
    networks:
      - balancer

networks:
  balancer:
    driver: "bridge"