version: '3'

services:
  server_1:
    image: nginx
    container_name: 'server_1'
    volumes:
      - ./server_1:/usr/share/nginx/html
    ports:
      - 7000:80
    networks:
      app_net:
        ipv4_address: 172.30.0.2

  server_2:
    image: nginx
    container_name: 'server_2'
    volumes:
      - ./server_2:/usr/share/nginx/html
    ports:
      - 7001:80
    networks:
      app_net:
        ipv4_address: 172.30.0.3

  reverse_proxy:
    image: nginx
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      app_net:
        ipv4_address: 172.30.0.4

networks:
  app_net:
    name: app_net
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24