version: '3'

services:
  ros-master:
    # image: ros:melodic
    build: ./ros_cui
    tty: true
    networks:
      ros_net:
        ipv4_address: 172.30.0.2
    environment: 
      - ROS_IP=172.30.0.2
      - ROS_MASTER_URI=http://172.30.0.2:11311

  ros-client:
    # image: ros:melodic
    build: ./ros_cui
    tty: true
    environment: 
      - ROS_IP=172.30.0.2
      - ROS_MASTER_URI=http://172.30.0.2:11311
    networks:
      ros_net:
        ipv4_address: 172.30.0.2

  ros-gui:
    # image: tiryoh/ros-desktop-vnc:melodic
    build: ./ros_gui
    tty: true
    ports:
      - 6080:80
    shm_size: 512m
    # environment: 
    #   - ROS_IP=172.30.0.3
    #   - ROS_MASTER_URI=http://172.30.0.2:11311
    networks:
      ros_net:
        ipv4_address: 172.30.0.3

networks:
  ros_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

