version: '3'

services:
  ros_master:
    image: ros:melodic
    tty: true
    command: roscore
    environment: 
      - ROS_IP=172.30.0.2
      - ROS_MASTER_URI=http://172.30.0.2:11311
    networks:
      ros_net:
        ipv4_address: 172.30.0.2

  ros_follower:
    image: ros:melodic
    depends_on:
          - ros_master
    tty: true
    command: rostopic list
    environment: 
      - ROS_IP=172.30.0.3
      - ROS_MASTER_URI=http://172.30.0.2:11311
    networks:
      ros_net:
        ipv4_address: 172.30.0.3
    restart: always

networks:
  ros_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
